# Generated by Django 4.2.7 on 2026-08-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='image',
            field=models.ImageField(upload_to='equipe/'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='image',
            field=models.ImageField(upload_to='equipements/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(upload_to='spaces/'),
        ),
    ]
