# Generated by Django 4.2.7 on 2026-08-24 11:47

from django.db import migrations, models
import django.db.models.deletion


def create_categories_from_roles(apps, schema_editor):
    Equipe = apps.get_model('application', 'Equipe')
    EquipeCategory = apps.get_model('application', 'EquipeCategory')
    categories = {}

    for member in Equipe.objects.exclude(role='').order_by('role'):
        role = (member.role or '').strip()
        if not role:
            continue
        category = categories.get(role)
        if category is None:
            category, _ = EquipeCategory.objects.get_or_create(name=role)
            categories[role] = category
        member.category = category
        member.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Catégorie d'équipe",
                'verbose_name_plural': "Catégories d'équipe",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='application.equipecategory'),
        ),
        migrations.RunPython(create_categories_from_roles, migrations.RunPython.noop),
    ]
